name = "kastans-workers"
main = "src/app.ts"
compatibility_date = "2024-09-25"
compatibility_flags = [ "nodejs_compat" ]

# Define default environment variables
[vars]
NODE_ENV = "production"
LOG_LEVEL = "debug"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true